# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
image:
  - Ubuntu2004
  - Visual Studio 2019
  - macos

init:
  - git config --global core.autocrlf input
build: off
cache:
  - node_modules
  - '%AppData%\npm-cache'

# what combinations to test
environment:
  matrix:
    - nodejs_version: 16
branches:
  only:
    - /master|^v\d+\.\d+\.\d+?(-\S*)?$/

platform:
  - x86
  - x64
  - arm64

for:
    ########## UBUNTU SPECIFIC CONFIGURATION ##########
  - matrix:
      only:
        - image: Ubuntu2004
        - fast_finish: true
    environment:
      CCACHE_TEMPDIR: /tmp/.ccache-temp
      CCACHE_COMPRESS: 1
      CC: "clang"
      CXX: "clang++"
    install:
      - sh: nvm install $nodejs_version
      - npm install
    build: off

    test_script:
      - node --version
      - npm --version

    deploy_script:
      - ci/prebuild-publish.sh %nodejs_version%

    ########## OSX SPECIFIC CONFIGURATION ##########
  - matrix:
      only:
        - image: macos
        - fast_finish: true
      exclude:
        - platform: x86
    environment:
      CCACHE_TEMPDIR: /tmp/.ccache-temp
      CCACHE_COMPRESS: 1
      CC: "clang"
      CXX: "clang++"
    install:
      - sh: nvm install $nodejs_version
      - npm install
    build: off

    test_script:
      - node --version
      - npm --version

    deploy_script:
      - ci/prebuild-publish.sh %nodejs_version%
    ########## Windows SPECIFIC CONFIGURATION ##########
  - matrix:
      only:
        - image: Visual Studio 2019
        - fast_finish: true
    platform: x64
    environment:
      PYTHON: C:\Python310-x64
      PYTHON_VERSION: 3.10
    init:
      - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
    install:
      - python --version
      - npm i npm@8 -g
      - python -m pip install gyp-next
      - ps: Install-Product node $env:nodejs_version
      - npm install
    build: off

    test_script:
      - node --version
      - npm --version

    deploy_script:
      - ci\prebuild-publish.bat %nodejs_version%
